server:
  port: 2000

spring:
  application:
    name: time-of-day-service
  config:
    import: optional:configserver:http://config-server:50000

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    instance-id: ${spring.application.name}:${random.int}
